apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crm
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: yugal47/saas-crm-user-service:latest
        ports:
          - containerPort: 8081
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: USER_SERVICE_DB_URL
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi
#        startupProbe:
#          httpGet:
#            path: /actuator/health
#            port: 8081
#          periodSeconds: 5
#          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 40
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  namespace: crm
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 8081
    targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crm
  name: crm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
      - name: crm-service
        image: yugal47/saas-crm-crm-service:latest
        ports:
          - containerPort: 8082
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: CRM_SERVICE_DB_URL
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 40
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  namespace: crm
  name: crm-service
spec:
  selector:
    app: crm-service
  ports:
  - port: 8082
    targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crm
  name: audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
      - name: audit-service
        image: yugal47/saas-crm-audit-service:latest
        ports:
          - containerPort: 8085
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: AUDIT_SERVICE_DB_URL
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 40
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  namespace: crm
  name: audit-service
spec:
  selector:
    app: audit-service
  ports:
  - port: 8085
    targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crm
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: yugal47/saas-crm-notification-service:latest
        ports:
          - containerPort: 8083
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: NOTIFICATION_SERVICE_DB_URL
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 40
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  namespace: crm
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 8083
    targetPort: 8083
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-service-storage
  namespace: crm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crm
  name: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
      - name: file-service
        image: yugal47/saas-crm-file-service:latest
        ports:
          - containerPort: 8084
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: FILE_SERVICE_DB_URL
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 40
          periodSeconds: 15
        volumeMounts:
          - name: file-storage
            mountPath: /data/files
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: file-service-storage
---
apiVersion: v1
kind: Service
metadata:
  namespace: crm
  name: file-service
spec:
  selector:
    app: file-service
  ports:
  - port: 8084
    targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crm
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: yugal47/saas-crm-gateway-service:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  namespace: crm
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crm
  name: reporting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: yugal47/saas-crm-reporting-service:latest
        ports:
          - containerPort: 8086
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: REPORTING_SERVICE_URL
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 40
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  namespace: crm
  name: reporting-service
spec:
  selector:
    app: reporting-service
  ports:
  - port: 8086
    targetPort: 8086
